SELECT TOP (1000) [BookingId]
      ,[UserId]
      ,[RoomId]
      ,[CheckInDate]
      ,[CheckOutDate]
      ,[TotalPrice]
      ,[Status]
      ,[CustomerName]
      ,[Phone]
      ,[RoomName]
      ,[Price]
  FROM [WebQuanLyKhachSan].[dbo].[Bookings]